feat : HCX-396 - HCX should generate URL for encryption and signing cert path
Swasth-Digital-Health-Foundation/hcx-platform pull request #361
Opened 2023-01-23 13:11 UTC by AbhiGaddi

2023-01-23 13:22 UTC, shiva-rakshith commented on hcx-apis/src/main/java/org/swasth/hcx/controllers/v1/ParticipantController.java
> +    @Value("${certificates.aws_accesskey}")
Are these required here?

2023-01-23 13:37 UTC, shiva-rakshith commented on hcx-apis/src/main/java/org/swasth/hcx/controllers/v1/ParticipantController.java
> +
Where is the signing cert path expiry field?

2023-01-23 13:37 UTC, shiva-rakshith commented on hcx-apis/src/main/resources/application.yml
> +  aws_accesskey : ${accesskey:}
keep the variable names in camel case

2023-01-23 13:37 UTC, shiva-rakshith commented on hcx-core/aws-client/src/main/java/org/swasth/AwsClient.java
> +    public void putObject(String folderName){
Give spaces between methods, maintain format.

2023-01-24 05:43 UTC, shiva-rakshith commented on hcx-apis/src/main/java/org/swasth/hcx/controllers/v1/ParticipantController.java
> +            awsClient.deleteMultipleObject(participantCode, bucketName);
If object is not in s3, will it throw an error.

2023-01-27 04:53 UTC, maheshkumargangula requested changes

2023-01-27 04:53 UTC, maheshkumargangula commented on hcx-apis/pom.xml
> +			<artifactId>aws-client</artifactId>
```suggestion
			<artifactId>cloud-storage-client</artifactId>
```

2023-01-27 04:53 UTC, maheshkumargangula commented on hcx-apis/src/main/java/org/swasth/hcx/config/AwsConfiguration.java
> + class AwsConfiguration {
Don't use names specific to a could service provider.

2023-01-27 04:53 UTC, maheshkumargangula commented on hcx-apis/src/main/java/org/swasth/hcx/controllers/v1/ParticipantController.java
> +    private void validateCreateParticipant(Map<String, Object> requestBody) throws ClientException {
Why do we have this code in controller?

2023-01-27 04:53 UTC, maheshkumargangula commented on hcx-apis/src/test/java/org/swasth/hcx/controllers/BaseSpec.java
> +        obj.put("certificates_type","cert_data");
Why did you introduce this parameter in the request body? There should not be any changes to the API Spec for implementation.

2023-02-13 12:42 UTC, maheshkumargangula approved these changes

2023-02-13 12:42 UTC, merged