HCX-754 : Implement async execution of creating mock participants
Swasth-Digital-Health-Foundation/hcx-platform pull request #532
Opened 2023-07-20 05:39 UTC by AbhiGaddi

2023-07-21 07:43 UTC, shiva-rakshith commented on hcx-onboard/src/main/java/org/swasth/hcx/services/OnboardService.java
> +    public CompletableFuture<Map<String, Object>> asyncMockParticipant(HttpHeaders headers, String action, CompletableFuture<Map<String, Object>> mockDetails, Map<String, Object> participantDetails)
Why this method required? Implement async execution for creatMockParticipant method only.

2023-07-28 07:13 UTC, maheshkumargangula requested changes

2023-07-28 07:13 UTC, maheshkumargangula commented on hcx-core/audit-indexer/src/main/resources/audit-mappings.json
> +      "type": "integer"
Are we storing the bytes value? Integer might not work. Do we have "number" as datatype. Please check for the limit.

2023-07-28 07:13 UTC, maheshkumargangula commented on hcx-onboard/src/main/java/org/swasth/hcx/services/OnboardService.java
> +                mockParticipant.remove(PRIVATE_KEY);
We should handle the Private Key access in a better way...

2023-08-03 12:17 UTC, maheshkumargangula approved these changes

2023-08-03 12:17 UTC, merged