Hcx apis feedback review changes
Swasth-Digital-Health-Foundation/hcx-platform pull request #8
Opened 2021-12-02 10:23 UTC by shiva-rakshith

2021-12-02 13:07 UTC, maheshkumargangula requested changes

2021-12-02 14:40 UTC, shiva-rakshith commented on hcx-apis/src/main/java/org/swasth/hcx/controllers/BaseController.java
> +        mandatoryHeaders.addAll(env.getProperty(Constants.JOSE_HEADERS, List.class));
Updated.

2021-12-02 14:40 UTC, shiva-rakshith commented on hcx-apis/src/main/java/org/swasth/hcx/controllers/BaseController.java
> +            kafkaClient.send(metadataTopic, "", metadataEvent);
Updated.

2021-12-02 14:40 UTC, shiva-rakshith commented on hcx-apis/src/main/java/org/swasth/hcx/controllers/v1/ClaimsController.java
> +    }*/
Updated.

2021-12-02 14:40 UTC, shiva-rakshith commented on hcx-apis/src/main/java/org/swasth/hcx/controllers/v1/PaymentsController.java
> +    /*@RequestMapping(value = "/request", method = RequestMethod.POST)
Updated.

2021-12-02 14:41 UTC, shiva-rakshith commented on hcx-apis/src/main/java/org/swasth/hcx/controllers/HealthController.java
> +        response.put(Constants.HEALTHY, allServiceHealthResult);
In line 27, inside the loop at lambda using normal boolean throwing an error.

2021-12-06 05:39 UTC, maheshkumargangula commented on hcx-apis/src/main/java/org/swasth/hcx/controllers/HealthController.java
> +        response.put(Constants.HEALTHY, allServiceHealthResult);
Don't need to use a lambda function here. Use normal for loop.

2021-12-06 07:20 UTC, shiva-rakshith commented on hcx-apis/src/main/java/org/swasth/hcx/controllers/HealthController.java
> +        response.put(Constants.HEALTHY, allServiceHealthResult);
Updated with suggested changes.

2021-12-06 09:18 UTC, maheshkumargangula requested changes

2021-12-06 09:18 UTC, maheshkumargangula commented on hcx-core/hcx-common/src/main/java/org/swasth/common/StringUtils.java
> +    public static HashMap<String,Object> decodeBase64String(String encodedString) throws Exception {
```suggestion
    public static Map<String,Object> decodeBase64String(String encodedString) throws Exception {
```

2021-12-06 10:43 UTC, maheshkumargangula approved these changes

2021-12-06 10:43 UTC, merged